### ISSUE TITLE
I made some errors during deployment

### ISSUE THREAD

**Issue by EaMarWi** [braydoncoyer/braydoncoyer.dev#166]
Braydoncoyer, hello. I made some errors during deployment. The error information is as follows.
```shell
Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error
--
21:50:54.657 | TypeError: Cannot read property 'multi_select' of undefined
21:50:54.657 | at /vercel/path0/.next/server/chunks/740.js:131:43
21:50:54.657 | at Array.map (<anonymous>)
21:50:54.657 | at convertToArticleList (/vercel/path0/.next/server/chunks/740.js:126:32)
21:50:54.657 | at getStaticProps (/vercel/path0/.next/server/pages/blog.js:490:109)
21:50:54.658 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:50:54.658 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:488:20)
21:50:54.658 | at async /vercel/path0/node_modules/next/dist/export/worker.js:253:36
21:50:54.658 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:54.659 |  
21:50:54.659 | Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
21:50:54.659 | TypeError: Cannot read property 'multi_select' of undefined
21:50:54.660 | at /vercel/path0/.next/server/chunks/740.js:131:43
21:50:54.660 | at Array.map (<anonymous>)
21:50:54.660 | at convertToArticleList (/vercel/path0/.next/server/chunks/740.js:126:32)
21:50:54.660 | at getStaticProps (/vercel/path0/.next/server/pages/index.js:164:102)
21:50:54.660 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:50:54.660 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:488:20)
21:50:54.660 | at async /vercel/path0/node_modules/next/dist/export/worker.js:253:36
21:50:54.660 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:54.661 | info  - Generating static pages (5/11)
21:50:55.214 |  
21:50:55.214 | Error occurred prerendering page "/about". Read more: https://nextjs.org/docs/messages/prerender-error
21:50:55.215 | TypeError: Cannot read property 'multi_select' of undefined
21:50:55.215 | at /vercel/path0/.next/server/chunks/740.js:131:43
21:50:55.215 | at Array.map (<anonymous>)
21:50:55.215 | at convertToArticleList (/vercel/path0/.next/server/chunks/740.js:126:32)
21:50:55.215 | at getStaticProps (/vercel/path0/.next/server/pages/about.js:334:102)
21:50:55.215 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:50:55.215 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:488:20)
21:50:55.215 | at async /vercel/path0/node_modules/next/dist/export/worker.js:253:36
21:50:55.215 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:55.219 | info  - Generating static pages (8/11)
21:50:55.236 |  
21:50:55.237 | Error occurred prerendering page "/blog/test". Read more: https://nextjs.org/docs/messages/prerender-error
21:50:55.237 | TypeError: Cannot read property 'profile_image_url' of undefined
21:50:55.237 | at getTwitterProfilePicture (/vercel/path0/.next/server/pages/blog/[slug].js:619:28)
21:50:55.237 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:50:55.237 | at async getStaticProps (/vercel/path0/.next/server/pages/blog/[slug].js:1105:28)
21:50:55.237 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:488:20)
21:50:55.237 | at async /vercel/path0/node_modules/next/dist/export/worker.js:253:36
21:50:55.237 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:55.239 |  
21:50:55.240 | Error occurred prerendering page "/community-wall". Read more: https://nextjs.org/docs/messages/prerender-error
21:50:55.240 | TypeError: Cannot read property 'messages' of null
21:50:55.240 | at CommunityWall (/vercel/path0/.next/server/pages/community-wall.js:327:42)
21:50:55.240 | at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
21:50:55.240 | at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
21:50:55.240 | at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
21:50:55.240 | at Object.exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
21:50:55.240 | at renderDocument (/vercel/path0/node_modules/next/dist/server/render.js:847:47)
21:50:55.240 | at renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:948:34)
21:50:55.241 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:50:55.241 | at async /vercel/path0/node_modules/next/dist/export/worker.js:253:36
21:50:55.241 |  
21:50:55.241 | > Build error occurred
21:50:55.241 | info  - Generating static pages (11/11)
21:50:55.242 | Error: Export encountered errors on following paths:
21:50:55.243 | /
21:50:55.243 | /about
21:50:55.243 | /blog
21:50:55.243 | /blog/[slug]: /blog/test
21:50:55.243 | /community-wall
21:50:55.243 | at /vercel/path0/node_modules/next/dist/export/index.js:397:19
21:50:55.244 | at runMicrotasks (<anonymous>)
21:50:55.244 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
21:50:55.244 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:55.244 | at async /vercel/path0/node_modules/next/dist/build/index.js:1010:17
21:50:55.244 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:55.244 | at async /vercel/path0/node_modules/next/dist/build/index.js:886:13
21:50:55.244 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
21:50:55.244 | at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:55:25)
21:50:55.286 | error Command failed with exit code 1.
21:50:55.287 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:50:55.297 | Error: Command "yarn run build" exited with 1

``` 

After checking for a long time, I don't know where the problem is. I really hope to get your help. In addition, can you briefly share the notation format of database page and change page? Although I speculated about the format of database page and change page according to your GitHub code, I'm afraid I didn't get the format right

**Comment by braydoncoyer** [comment]
I'll be releasing the Notion template that goes along with this open source portfolio. Once the template is available, deploying should be very straightforward.

**Comment by braydoncoyer** [comment]
Looping back around to inform you that I just released a public-facing database template that is based off of what I use for this repository.

https://www.notion.so/0d3e00c6bbe54231897b9fcbc7747f78?v=4d7f0006d9a144b5bd8b9251f2ec39cd
