### ISSUE TITLE
I am getting an error with the Supabase integration... Will you be willing to share your DB schema from Supabase ?

### ISSUE THREAD

**Issue by arya1105** [braydoncoyer/braydoncoyer.dev#175]
Seems like the codebase is referring to Supabase tables and stored procs ... How do I replicate that ?

    at new SupabaseClient (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\node_modules\@supabase\supabase-js\dist\main\SupabaseClient.js:51:19)
    at createClient (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\node_modules\@supabase\supabase-js\dist\main\index.js:29:12)
    at eval (webpack-internal:///./lib/hooks/useSupabase.ts:14:91)
    at Object../lib/hooks/useSupabase.ts (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\.next\server\pages\_app.js:22:1)
    at __webpack_require__ (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:15:76)
    at Object../pages/_app.tsx (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\.next\server\pages\_app.js:33:1)
    at __webpack_require__ (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\.next\server\pages\_app.js:118:39)
    at C:\Users\raish\Documents\Notion to Website\WebsiteSecondDraft\.next\server\pages\_app.js:119:28 {
  page: '/'
}

**Comment by braydoncoyer** [comment]
Here's what my "reactions" table looks like.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/38799309/176473408-14f0b205-36c9-4e7b-8025-446aaf44e797.png">


And here is what my 'pages' table looks like (tracking page views)

<img width="815" alt="image" src="https://user-images.githubusercontent.com/38799309/176473500-4ae7bc3a-4120-45cc-82d6-53ddd8bc7a72.png">

You should be able to derive column names from the code in the `api` directory.

**Comment by arya1105** [comment]
ok, I will try that. Thanks much!

**Comment by Sasha95** [comment]
can i see your database schema?
